server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/**
  redis:
    host: 192.168.174.140
    port: 6379
    database: 10

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: nero-api-admin-consumer
  protocol:
    name: dubbo
    port: 10086
  registry:
    id: nacos-registry
    address: nacos://192.168.220.1:8848

